name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: martinmol2007
          base: ""
          config_timezone: Europe/Madrid
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
 # Imagen 2: fortune
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.fortune.svg
          token: NOT_NEEDED
          user: martinmol2007
          base: ""
          plugin_fortune: yes
